apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grpc-python
resources:
- python-grpc-namespace.yaml
- server

labels:
  - pairs:
      semashking/learning/applications/language: python
    includeTemplates: true