apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces/shared/shared-namespace.yaml

helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.24.1
  releaseName: vault
  namespace: shared
  valuesFile: default-vault-values.yaml
  